### ISSUE TITLE
Question :: Howto enable debug traces

### ISSUE THREAD

**Issue by shamb0** [ethereum-optimism/optimism-monorepo#240]
Hey There,

Very basic question, tried to execute the test with command "yarn run test ./test/contracts/ovm/execution-manager/ExecutionManager.executeCall.spec.ts ", but I don't know howto activate the internal traces both from *.sol & *.ts

Long console log in stripped form ...

```shell
vagrant@vagrant:/vagrant/ws-020-blocks/demo-002-optimism/optimism-monorepo/packages/contracts$ yarn run test ./test/contracts/ovm/execution-manager/ExecutionManager.executeCall.spec.ts 
yarn run v1.22.5
$ yarn run test:contracts ./test/contracts/ovm/execution-manager/ExecutionManager.executeCall.spec.ts
$ cross-env SOLPP_FLAGS="FLAG_IS_TEST,FLAG_IS_DEBUG" buidler test --show-stack-traces ./test/contracts/ovm/execution-manager/ExecutionManager.executeCall.spec.ts
Compiling...

Compiled 61 contracts successfully


  Execution Manager -- TX/Call Execution Functions
    executeNonEOACall
      ✓ fails if the provided timestamp is 0 (118ms)
      ✓ properly executes a raw call -- 0 param (151ms)
    executeEOACall
      ✓ properly executes a raw call -- 0 param (303ms)
      ✓ increments the senders nonce (189ms)
      ✓ properly executes a raw call -- 1 param (265ms)
      ✓ reverts when it makes a call that reverts
      ✓ reverts when it makes a call that fails a require (218ms)


  7 passing (13s)

Done in 37.86s.

```

Any configuration missing ?

Thanks

**Comment by ben-chain** [comment]
Hey there, thanks for the question :)

We use [debug](https://www.npmjs.com/package/debug) for our ts logging so you can use `env DEBUG="your-logger-name-here" yarn test ...` to look at things logged in js (at the top of our testfiles, you should see a `getLogger("logger-name")`.  To debug internal EVM traces is a little more difficult -- one option is to use [debug_traceTransaction](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction) by adding a line to the test which says `const aTrace = ethers.provider.send('debug_traceTransaction', [<desired arguments>]`.

Hope this helps!

**Comment by shamb0** [comment]
Hi @ben-chain,

Great, thanks for nice note. Will explore more and get back ...
