### ISSUE TITLE
ovm-toolchain requires node v10 which is way outdated

### ISSUE THREAD

**Issue by petejkim** [ethereum-optimism/optimism-monorepo#364]
**Describe the bug**
ovm-toolchain package requires node v10 which is way outdated, current LTS is v14

**Expected behavior**
It should allow the installation and use on newer versions of node by specifying the "engine" field to be ">= 10" instead.

Seems to work just fine when force-installed with `yarn install --ignore-engines`, so it's safe to change.

**Comment by tynes** [comment]
We have deprecated the ovm-toolchain package and the packages remaining in this repo should work with anything greater than or equal to node v10
