### ISSUE TITLE
The OVM tutorial link in Readme.md is broken.

### ISSUE THREAD

**Issue by john-a-m** [ethereum-optimism/optimism-monorepo#386]
It points to https://github.com/ethereum-optimism/ERC20-Example , which doesn't appear to exist anymore. Similarly there is a broken link on https://docs.optimism.io/developer-documentation/erc20-tutorial that points to https://github.com/ethereum-optimism/optimism-monorepo/tree/master/packages/examples .

**Comment by atnjqt** [comment]
Yes I am also wondering about the last section of README, regarding docker composer... there is no Dockerfile or docker-compose.yml example given!

honestly not sure what running the 'fullnode' on docker accomplishes but still interesting

**Comment by tynes** [comment]
Please see the updated example: https://github.com/ethereum-optimism/optimism-tutorial
